apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  project: default
  source:
    chart: airflow
    helm:
      values: |
      createUserJob:
        useHelmHooks: false
      migrateDatabaseJob:
        useHelmHooks: false
    repoURL: https://airflow-helm.github.io/charts 
    targetRevision: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


