
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  project: default
  source:
    path: airflow/
    repoURL: https://github.com/schemaitat/k8s-cluster.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-k8s-celery.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true